# reward for target band gap near 3.0 eV and low energy above hull
_target_: rewards.reward.Reward

root_dir: rewards
reduce: min

mattersim_potential_path: /mnt/shared-storage-user/zhangsizhe/mattergen_steering_2/checkpoints/mattersim/mattersim-v1.0.0-1M.pth
mattersim_reference_dataset_path: /mnt/shared-storage-user/zhangsizhe/mattergen/data-release/alex-mp/reference_MP2020correction.gz

prop_cfg:
  - name: band_gap
    calculator:
      _target_: rewards.calculators.ALIGNN
      root_dir: rewards/bandgap
      task: band_gap
      device: ${device}
      silent: true
    target: 3.0
    minv: 0.0
    maxv: 2.0

  - name: ehull
    calculator:
      _target_: rewards.calculators.MatterSim
      root_dir: rewards/ehull
      task: ehull
      device: ${device}
      potential_load_path: ${reward.mattersim_potential_path}
      reference_dataset_path: ${reward.mattersim_reference_dataset_path}
      silent: true
    target: descending
    minv: 0.0
    maxv: 0.5

reward_threshold: 0.75
