# @package _global_
expname: matinvent_baseline_700_1000_seed
results_dir: exp_res_seed
model:
  model_path: /mnt/shared-storage-user/zhangsizhe/mattergen_steering_2/checkpoints/my_train_mattergen_base
  finetune_cfg:
    timestep_schedule:
      - loop_start: 0
        loop_end: 100
        timestep_start: 700
        timestep_end: 1000
