# @package _global_
expname: matinvent_baseline_ehull_curriculum_0_40__300_700__40_60__0_300
results_dir: exp_res_all
model:
  model_path: /mnt/shared-storage-user/zhangsizhe/mattergen_steering_2/checkpoints/my_train_mattergen_base
  finetune_cfg:
    timestep_schedule:
      - loop_start: 0
        loop_end: 40
        timestep_start: 300
        timestep_end: 700
      - loop_start: 40
        loop_end: 60
        timestep_start: 0
        timestep_end: 300
