# @package _global_
expname: matinvent_baseline_ehull_sliding_0_300_step_100_loops_10
results_dir: exp_res_all

model:
  model_path: /mnt/shared-storage-user/zhangsizhe/mattergen_steering_2/checkpoints/my_train_mattergen_base
  finetune_cfg:
    timestep_schedule:
      - loop_start: 0
        loop_end: 10
        timestep_start: 0
        timestep_end: 300
      - loop_start: 10
        loop_end: 20
        timestep_start: 100
        timestep_end: 400
      - loop_start: 20
        loop_end: 30
        timestep_start: 200
        timestep_end: 500
      - loop_start: 30
        loop_end: 40
        timestep_start: 300
        timestep_end: 600
      - loop_start: 40
        loop_end: 50
        timestep_start: 400
        timestep_end: 700
      - loop_start: 50
        loop_end: 60
        timestep_start: 500
        timestep_end: 800
